export const dummyTherapists = [
  {
    email: "john.doe@example.com",
    name: "John Doe",
    phone: "123-456-7890",
    dob: "1985-06-15",
    location: "New York, NY",
    verified: true,
    registrationNumber: "REG123456",
    degree: "PhD in Psychology",
    experience: "10 years",
    specialization: "Cognitive Behavioral Therapy",
    meetDuration: "60 minutes",
    sessionCost: "150",
    sessionMode: "Online",
    RCI_document: "rci_doc_john_doe.pdf",
    Malpractice_Insurance_document: "malpractice_insurance_john_doe.pdf",
    profilePic: "profile_pic_john_doe.jpg",
    bio: "Experienced psychologist specializing in cognitive behavioral therapy.",
    stars: 5,
  },
  {
    email: "jane.smith@example.com",
    name: "Jane Smith",
    phone: "234-567-8901",
    dob: "1990-02-20",
    location: "Los Angeles, CA",
    verified: false,
    registrationNumber: "REG654321",
    degree: "Master's in Clinical Psychology",
    experience: "5 years",
    specialization: "Family Therapy",
    meetDuration: "45 minutes",
    sessionCost: "120",
    sessionMode: "In-Person",
    RCI_document: "rci_doc_jane_smith.pdf",
    Malpractice_Insurance_document: null,
    profilePic: "profile_pic_jane_smith.jpg",
    bio: "Dedicated therapist focused on family and relationship issues.",
    stars: 4,
  },
  {
    email: "will.johnson@example.com",
    name: "Will Johnson",
    phone: "345-678-9012",
    dob: "1978-11-05",
    location: "Chicago, IL",
    verified: true,
    registrationNumber: "REG789012",
    degree: "Doctor of Medicine in Psychiatry",
    experience: "15 years",
    specialization: "Psychopharmacology",
    meetDuration: "30 minutes",
    sessionCost: "200",
    sessionMode: "Online",
    RCI_document: "rci_doc_will_johnson.pdf",
    Malpractice_Insurance_document: "malpractice_insurance_will_johnson.pdf",
    profilePic: "profile_pic_will_johnson.jpg",
    bio: "Experienced psychiatrist with a focus on psychopharmacology.",
    stars: 5,
  },
  {
    email: "mary.jones@example.com",
    name: "Mary Jones",
    phone: "456-789-0123",
    dob: "1982-07-22",
    location: "Houston, TX",
    verified: true,
    registrationNumber: "REG345678",
    degree: "PhD in Counseling Psychology",
    experience: "12 years",
    specialization: "Trauma Therapy",
    meetDuration: "60 minutes",
    sessionCost: "160",
    sessionMode: "In-Person",
    RCI_document: "rci_doc_mary_jones.pdf",
    Malpractice_Insurance_document: "malpractice_insurance_mary_jones.pdf",
    profilePic: "profile_pic_mary_jones.jpg",
    bio: "Expert in trauma therapy with a compassionate approach.",
    stars: 5,
  },
  {
    email: "mike.brown@example.com",
    name: "Mike Brown",
    phone: "567-890-1234",
    dob: "1987-03-14",
    location: "Phoenix, AZ",
    verified: false,
    registrationNumber: "REG901234",
    degree: "Master's in Mental Health Counseling",
    experience: "7 years",
    specialization: "Addiction Counseling",
    meetDuration: "50 minutes",
    sessionCost: "130",
    sessionMode: "Online",
    RCI_document: "rci_doc_mike_brown.pdf",
    Malpractice_Insurance_document: null,
    profilePic: "profile_pic_mike_brown.jpg",
    bio: "Passionate about helping individuals overcome addiction.",
    stars: 4,
  },
  {
    email: "lisa.white@example.com",
    name: "Lisa White",
    phone: "678-901-2345",
    dob: "1992-12-01",
    location: "San Francisco, CA",
    verified: true,
    registrationNumber: "REG112233",
    degree: "PhD in Clinical Psychology",
    experience: "6 years",
    specialization: "Depression and Anxiety",
    meetDuration: "60 minutes",
    sessionCost: "140",
    sessionMode: "In-Person",
    RCI_document: "rci_doc_lisa_white.pdf",
    Malpractice_Insurance_document: "malpractice_insurance_lisa_white.pdf",
    profilePic: "profile_pic_lisa_white.jpg",
    bio: "Specializes in treating depression and anxiety disorders.",
    stars: 5,
  },
  {
    email: "david.moore@example.com",
    name: "David Moore",
    phone: "789-012-3456",
    dob: "1980-09-10",
    location: "Miami, FL",
    verified: true,
    registrationNumber: "REG445566",
    degree: "Doctor of Psychology (PsyD)",
    experience: "11 years",
    specialization: "Child and Adolescent Therapy",
    meetDuration: "45 minutes",
    sessionCost: "150",
    sessionMode: "Online",
    RCI_document: "rci_doc_david_moore.pdf",
    Malpractice_Insurance_document: "malpractice_insurance_david_moore.pdf",
    profilePic: "profile_pic_david_moore.jpg",
    bio: "Focused on child and adolescent therapy with a holistic approach.",
    stars: 5,
  },
  {
    email: "susan.miller@example.com",
    name: "Susan Miller",
    phone: "890-123-4567",
    dob: "1984-08-18",
    location: "Denver, CO",
    verified: false,
    registrationNumber: "REG778899",
    degree: "Master's in Social Work",
    experience: "9 years",
    specialization: "Community Counseling",
    meetDuration: "50 minutes",
    sessionCost: "110",
    sessionMode: "In-Person",
    RCI_document: "rci_doc_susan_miller.pdf",
    Malpractice_Insurance_document: null,
    profilePic: "profile_pic_susan_miller.jpg",
    bio: "Community counselor with a focus on social issues.",
    stars: 4,
  },
  {
    email: "paul.wilson@example.com",
    name: "Paul Wilson",
    phone: "901-234-5678",
    dob: "1975-04-25",
    location: "Seattle, WA",
    verified: true,
    registrationNumber: "REG990011",
    degree: "PhD in Neuropsychology",
    experience: "20 years",
    specialization: "Neuropsychological Assessment",
    meetDuration: "90 minutes",
    sessionCost: "220",
    sessionMode: "In-Person",
    RCI_document: "rci_doc_paul_wilson.pdf",
    Malpractice_Insurance_document: "malpractice_insurance_paul_wilson.pdf",
    profilePic: "profile_pic_paul_wilson.jpg",
    bio: "Highly experienced in neuropsychological assessments and treatments.",
    stars: 5,
  },
  {
    email: "emma.davis@example.com",
    name: "Emma Davis",
    phone: "012-345-6789",
    dob: "1995-11-30",
    location: "Boston, MA",
    verified: false,
    registrationNumber: "REG223344",
    degree: "Master's in Counseling",
    experience: "3 years",
    specialization: "Stress Management",
    meetDuration: "40 minutes",
    sessionCost: "100",
    sessionMode: "Online",
    RCI_document: "rci_doc_emma_davis.pdf",
    Malpractice_Insurance_document: null,
    profilePic: "profile_pic_emma_davis.jpg",
    bio: "Focused on helping individuals manage and reduce stress effectively.",
    stars: 4,
  },
];
