import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nv from "@/components/Nv"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-100`}>
        <Nv/>
        <main className="mx-2 md:mx-3 lg:mx-5">
          {children}
        </main>
      </body>
    </html>
  );
}
